# Generated by Django 4.1 on 2022-08-08 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_show_todo_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='importance',
        ),
        migrations.AddField(
            model_name='todo',
            name='color',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Importance',
        ),
    ]
