# Generated by Django 4.1 on 2022-08-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_todo_importance_todo_color_todo_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='color',
        ),
    ]
